export const RARITIES = ['common', 'uncommon', 'rare', 'epic', 'legendary', 'mythic'];

export const RARITY_RANK = Object.fromEntries(RARITIES.map((r, i) => [r, i]));

export const TRASH = [
  // --- commons, everywhere ---
  { id: 'peel', name: 'Banana Peel', rarity: 'common', value: 1, icon: '🍌', quip: 'The original slapstick DLC.' },
  { id: 'cup', name: 'Iced Latte Tomb', rarity: 'common', value: 1, icon: '🥤', quip: 'Someone paid $7 for this melted ice.' },
  { id: 'sock', name: 'Mystery Sock', rarity: 'common', value: 1, icon: '🧦', quip: 'Its twin is in a better place.' },
  { id: 'ketchup', name: 'Ketchup Packet', rarity: 'common', value: 1, icon: '🍅', quip: 'Unopened. A miracle. A blessing.' },
  { id: 'fry', name: 'Sad Fry', rarity: 'common', value: 1, icon: '🍟', quip: 'The last of its people.' },
  { id: 'fork', name: 'Veteran Fork', rarity: 'common', value: 1, icon: '🍴', quip: 'Survived twelve takeout wars.' },
  { id: 'straw', name: 'Paper Straw', rarity: 'common', value: 1, icon: '🧋', quip: 'It lasted forty seconds. Respect.' },
  { id: 'receipt', name: 'Receipt Scroll', rarity: 'common', value: 2, icon: '🧾', quip: 'Four feet long. They bought one gum.' },
  { id: 'napkin', name: 'Cry Napkin', rarity: 'common', value: 1, icon: '🧻', quip: 'It just says HELP and a goose.' },
  { id: 'coupon', name: 'Expired Coupon', rarity: 'common', value: 2, icon: '🎫', quip: 'Died in 2019. Still has hope.' },
  { id: 'stick', name: 'Popsicle Stick', rarity: 'common', value: 1, icon: '🍦', quip: 'The stick remembers the ice cream.' },
  { id: 'punch', name: 'Loyalty Card', rarity: 'common', value: 2, icon: '💳', quip: 'One punch. They never came back.' },
  { id: 'menu', name: 'Wet Menu', rarity: 'common', value: 1, icon: '📋', quip: "Tuesday's soup is also Thursday's soup." },
  { id: 'lid', name: 'Orphan Cup Lid', rarity: 'common', value: 1, icon: '⭕', quip: 'Still looking for its cup.' },

  // --- diner ---
  { id: 'grease', name: 'Ancient Grease', rarity: 'uncommon', value: 8, icon: '🛢️', loc: 'diner', quip: 'It has a union. It has demands.' },
  { id: 'waffle', name: 'Waffle Archaeology', rarity: 'uncommon', value: 10, icon: '🧇', loc: 'diner', quip: 'Carbon dated to brunch.' },
  { id: 'special', name: "Today's Special", rarity: 'rare', value: 55, icon: '🍽️', loc: 'diner', quip: 'It is always meatloaf. Always.' },
  { id: 'juke', name: 'Jukebox Button', rarity: 'rare', value: 70, icon: '🎵', loc: 'diner', quip: 'Still playing one sad song.' },
  { id: 'meatball', name: 'Sentient Meatball', rarity: 'epic', value: 420, icon: '🧆', loc: 'diner', quip: 'It winked. You winked back. Fine.' },
  { id: 'firstfry', name: 'The First Fry', rarity: 'legendary', value: 6000, icon: '✨', loc: 'diner', quip: 'Still salty. Historically salty.' },

  // --- grocery ---
  { id: 'yogurt', name: 'Optimistic Yogurt', rarity: 'uncommon', value: 9, icon: '🥛', loc: 'grocery', quip: 'Expired. Believes in itself anyway.' },
  { id: 'avocado', name: 'Avocado Window', rarity: 'uncommon', value: 12, icon: '🥑', loc: 'grocery', quip: 'Ripe for twelve minutes last March.' },
  { id: 'barcode', name: 'Rebel Barcode', rarity: 'rare', value: 60, icon: '📟', loc: 'grocery', quip: 'It scans as "raccoon." Correct.' },
  { id: 'couponbook', name: 'Coupon Grimoire', rarity: 'rare', value: 80, icon: '📖', loc: 'grocery', quip: 'Buy one dumpster, get one free.' },
  { id: 'rotisserie', name: 'Lost Rotisserie', rarity: 'epic', value: 480, icon: '🍗', loc: 'grocery', quip: 'Hot. Or haunted. Same temperature.' },
  { id: 'manager', name: "Night Manager's Keys", rarity: 'legendary', value: 7200, icon: '🔑', loc: 'grocery', quip: 'They open the cereal dimension.' },

  // --- mall ---
  { id: 'airpod', name: 'Lone AirPod', rarity: 'uncommon', value: 14, icon: '🎧', loc: 'mall', quip: 'Its sibling is in a washing machine.' },
  { id: 'pretzel', name: 'Mall Pretzel Relic', rarity: 'uncommon', value: 11, icon: '🥨', loc: 'mall', quip: 'Salt older than the food court.' },
  { id: 'kiosk', name: 'Kiosk Business Card', rarity: 'rare', value: 75, icon: '💼', loc: 'mall', quip: 'Hair straightener AND a timeshare.' },
  { id: 'directory', name: 'You Are Here', rarity: 'rare', value: 90, icon: '🗺️', loc: 'mall', quip: 'You are, unfortunately, here.' },
  { id: 'fountain', name: 'Wishing Coin Hoard', rarity: 'epic', value: 540, icon: '🪙', loc: 'mall', quip: 'Dreams of a raccoon. Granted.' },
  { id: 'santa', name: 'Mall Santa List', rarity: 'legendary', value: 8000, icon: '🎅', loc: 'mall', quip: 'You are on it. Twice. Naughty.' },

  // --- park ---
  { id: 'wrist', name: 'Concert Wristband', rarity: 'uncommon', value: 13, icon: '🎟️', loc: 'park', quip: 'Band forgotten. Night immortal.' },
  { id: 'glow', name: 'Retired Glowstick', rarity: 'uncommon', value: 12, icon: '🌟', loc: 'park', quip: 'The rave ended. It did not.' },
  { id: 'churro', name: 'Churro Staff', rarity: 'rare', value: 85, icon: '🪵', loc: 'park', quip: 'A weapon and a dessert.' },
  { id: 'mascot', name: 'Mascot Head', rarity: 'rare', value: 110, icon: '🦊', loc: 'park', quip: 'Still smiling. Against its will.' },
  { id: 'fastpass', name: 'Golden Fastpass', rarity: 'epic', value: 620, icon: '🏅', loc: 'park', quip: 'Skip the line. Become the line.' },
  { id: 'coaster', name: 'Entire Coaster Wheel', rarity: 'legendary', value: 9000, icon: '🎢', loc: 'park', quip: 'It still clicks. So do you.' },

  // --- fancy ---
  { id: 'oyster', name: 'Regret Oyster', rarity: 'uncommon', value: 16, icon: '🦪', loc: 'fancy', quip: 'Someone paid $28 to be brave.' },
  { id: 'napkinring', name: 'Silver Napkin Ring', rarity: 'uncommon', value: 18, icon: '💍', loc: 'fancy', quip: 'The napkin escaped. The ring stayed.' },
  { id: 'sommelier', name: 'Sommelier Tears', rarity: 'rare', value: 120, icon: '🍷', loc: 'fancy', quip: 'Notes of dumpster. Finish: destiny.' },
  { id: 'reservation', name: 'Fake Reservation', rarity: 'rare', value: 100, icon: '📞', loc: 'fancy', quip: 'Name: Monsieur Dumpster.' },
  { id: 'recipe', name: "Chef's Cursed Recipe", rarity: 'epic', value: 780, icon: '📜', loc: 'fancy', quip: 'Step one: the alley. Step two: fame.' },
  { id: 'michelin', name: 'Stolen Star', rarity: 'legendary', value: 12000, icon: '⭐', loc: 'fancy', quip: 'You are now a restaurant. Congrats.' },

  // --- tech ---
  { id: 'usb', name: 'USB final_final2', rarity: 'uncommon', value: 20, icon: '💾', loc: 'tech', quip: 'Do not plug this in. Plug this in.' },
  { id: 'hoodie', name: 'Free Hoodie', rarity: 'uncommon', value: 17, icon: '👕', loc: 'tech', quip: 'Worth three internships.' },
  { id: 'standup', name: 'Standup Notes', rarity: 'rare', value: 130, icon: '📝', loc: 'tech', quip: '"What I did yesterday: dumpster."' },
  { id: 'hover', name: 'Broken Hoverboard', rarity: 'rare', value: 150, icon: '🛹', loc: 'tech', quip: 'It hovers emotionally.' },
  { id: 'pivot', name: 'Pivot Slide Deck', rarity: 'epic', value: 900, icon: '📊', loc: 'tech', quip: 'Seventeen slides. One raccoon.' },
  { id: 'unicorn', name: 'Seed Round Leftovers', rarity: 'legendary', value: 16000, icon: '🦄', loc: 'tech', quip: 'Burn rate: one dumpster/hour.' },

  // --- airport ---
  { id: 'neck', name: 'Neck Pillow Fossil', rarity: 'uncommon', value: 19, icon: '🛬', loc: 'airport', quip: 'It has seen things. So have you.' },
  { id: 'keycard', name: 'Hotel Keycard 412', rarity: 'uncommon', value: 22, icon: '🏨', loc: 'airport', quip: 'Do not go to room 412.' },
  { id: 'luggage', name: 'Orphan Suitcase', rarity: 'rare', value: 160, icon: '🧳', loc: 'airport', quip: 'It circles the carousel forever.' },
  { id: 'gate', name: 'Gate B12 Sign', rarity: 'rare', value: 140, icon: '🚪', loc: 'airport', quip: 'Delayed. Like your enemies.' },
  { id: 'duty', name: 'Duty-Free Mountain', rarity: 'epic', value: 1100, icon: '🛍️', loc: 'airport', quip: 'Perfume, chocolate, crimes.' },
  { id: 'passport', name: "Someone's Passport", rarity: 'legendary', value: 18000, icon: '📘', loc: 'airport', quip: 'The photo is a raccoon. Huh.' },

  // --- casino ---
  { id: 'chip', name: 'Lucky? Chip', rarity: 'uncommon', value: 24, icon: '🎰', loc: 'casino', quip: 'It is not lucky. You might be.' },
  { id: 'tie', name: "World's Okayest Tie", rarity: 'uncommon', value: 21, icon: '👔', loc: 'casino', quip: 'Worn during a legendary L.' },
  { id: 'comp', name: 'Buffet Comp', rarity: 'rare', value: 180, icon: '🦐', loc: 'casino', quip: 'All you can scoop.' },
  { id: 'dice', name: 'Loaded Dice', rarity: 'rare', value: 200, icon: '🎲', loc: 'casino', quip: 'They only roll dumpster.' },
  { id: 'jackpot', name: 'Jackpot Ticket', rarity: 'epic', value: 1400, icon: '💰', loc: 'casino', quip: 'The prize was more trash. Perfect.' },
  { id: 'house', name: 'The House', rarity: 'legendary', value: 24000, icon: '🏠', loc: 'casino', quip: 'You scooped the house. It lost.' },

  // --- nasa / moon ---
  { id: 'tang', name: 'Vintage Tang', rarity: 'uncommon', value: 30, icon: '🧃', loc: 'nasa', quip: 'The drink of champions and raccoons.' },
  { id: 'patch', name: 'Mission Patch', rarity: 'uncommon', value: 28, icon: '🚀', loc: 'nasa', quip: 'Mission: snacks.' },
  { id: 'moonboot', name: 'One Moon Boot', rarity: 'rare', value: 260, icon: '🥾', loc: 'nasa', quip: 'One small scoop for raccoonkind.' },
  { id: 'alien', name: 'Alien Takeout', rarity: 'rare', value: 300, icon: '👽', loc: 'nasa', quip: 'Receipt in a language of grease.' },
  { id: 'gravity', name: 'Spilled Gravity', rarity: 'epic', value: 2000, icon: '🌌', loc: 'nasa', quip: 'It goes in the bag. Physics cries.' },
  { id: 'tuesday', name: 'The Concept of Tuesday', rarity: 'legendary', value: 40000, icon: '📅', loc: 'nasa', quip: 'Heavy. Soggy. Recurs weekly.' },
  { id: 'moondeed', name: "The Moon's Dumpster Deed", rarity: 'mythic', value: 250000, icon: '🌙', loc: 'nasa', quip: 'Capitalism works in a vacuum.' },
  { id: 'lastdump', name: 'The Last Dumpster', rarity: 'mythic', value: 400000, icon: '🪐', loc: 'nasa', quip: 'There is no more trash. You won. Keep scooping.' },
];

export const LOCATIONS = [
  {
    id: 'diner',
    name: 'Behind the Diner',
    blurb: 'The grease is older than some countries.',
    neon: 'EAT HERE OR ELSE',
    sky: 'diner',
    mult: 1,
    capsNeeded: 0,
    travelCost: 0,
  },
  {
    id: 'grocery',
    name: 'Grocery Night Shift',
    blurb: 'Yogurt that expired with dignity.',
    neon: '24 HOUR MELONS',
    sky: 'grocery',
    mult: 2.2,
    capsNeeded: 18,
    travelCost: 60,
  },
  {
    id: 'mall',
    name: 'Mall Food Court',
    blurb: 'A food court with no food. Only court.',
    neon: 'SALES THAT HURT',
    sky: 'mall',
    mult: 4.5,
    capsNeeded: 36,
    travelCost: 320,
  },
  {
    id: 'park',
    name: 'Theme Park Close',
    blurb: 'The mascot clocked out. You clocked in.',
    neon: 'FUN UNTIL 9',
    sky: 'park',
    mult: 9,
    capsNeeded: 60,
    travelCost: 1400,
  },
  {
    id: 'fancy',
    name: 'Five-Star Alley',
    blurb: 'They plate garbage. You un-plate it.',
    neon: 'RESERVATIONS ONLY',
    sky: 'fancy',
    mult: 20,
    capsNeeded: 95,
    travelCost: 6500,
  },
  {
    id: 'tech',
    name: 'Tech Campus Bins',
    blurb: 'Free snacks, free hoodies, free IP.',
    neon: 'MOVE FAST',
    sky: 'tech',
    mult: 48,
    capsNeeded: 140,
    travelCost: 28000,
  },
  {
    id: 'airport',
    name: 'Airport Carousel',
    blurb: 'Lost bags go to a better raccoon.',
    neon: 'NOW BOARDING',
    sky: 'airport',
    mult: 110,
    capsNeeded: 190,
    travelCost: 120000,
  },
  {
    id: 'casino',
    name: 'Casino Back Alley',
    blurb: 'The house always scoops.',
    neon: 'WHAT HAPPENS HERE',
    sky: 'casino',
    mult: 260,
    capsNeeded: 250,
    travelCost: 520000,
  },
  {
    id: 'nasa',
    name: 'Low Orbit Leftovers',
    blurb: 'NASA threw out the moon. Your move.',
    neon: 'NO RACCOONS IN SPACE',
    sky: 'nasa',
    mult: 700,
    capsNeeded: 330,
    travelCost: 2.4e6,
  },
];

export const UPGRADES = [
  {
    id: 'paw',
    name: 'Paw Power',
    icon: '🐾',
    desc: 'Grab more junk per scoop. Your paws are becoming a municipal issue.',
    baseCost: 12,
    rate: 1.17,
    section: 'gear',
    next: (lv) => `Next scoop: ${1 + lv + 1} junk`,
    current: (lv) => `${1 + lv} junk / scoop`,
  },
  {
    id: 'bag',
    name: 'Bigger Bag',
    icon: '🎒',
    desc: '+4 pockets. A trash bag with a five-year plan.',
    baseCost: 16,
    rate: 1.15,
    section: 'gear',
    next: (lv) => `Capacity ${8 + (lv + 1) * 4}`,
    current: (lv) => `Holds ${8 + lv * 4}`,
  },
  {
    id: 'speed',
    name: 'Caffeinated Wrists',
    icon: '☕',
    desc: 'Scoop faster. You watched a squirrel do it and took notes.',
    baseCost: 22,
    rate: 1.2,
    max: 22,
    section: 'gear',
    next: (lv) => (lv >= 22 ? 'MAX' : '8% faster scoops'),
    current: (lv) => `Level ${lv}`,
  },
  {
    id: 'value',
    name: 'Shady Appraisal',
    icon: '😏',
    desc: '+15% sell value. Uncle Gary taught you to lie with confidence.',
    baseCost: 35,
    rate: 1.21,
    unlock: (s) => s.stats.sold >= 1,
    unlockHint: 'Sell your first bag',
    section: 'gear',
    next: (lv) => `+${(lv + 1) * 15}% value`,
    current: (lv) => `+${lv * 15}% value`,
  },
  {
    id: 'crit',
    name: 'Sticky Fingers',
    icon: '✨',
    desc: '+2.5% critical scoop (bonus junk). "It fell in my bag."',
    baseCost: 70,
    rate: 1.23,
    max: 18,
    unlock: (s) => s.lifetimeCoins >= 40,
    unlockHint: 'Earn 40¢ lifetime',
    section: 'gear',
    next: (lv) => (lv >= 18 ? 'MAX' : `Crit ${Math.min(45, 3 + (lv + 1) * 2.5).toFixed(1)}%`),
    current: (lv) => `Crit ${Math.min(45, 3 + lv * 2.5).toFixed(1)}%`,
  },
  {
    id: 'luck',
    name: 'Lucky Nose',
    icon: '👃',
    desc: 'Rarer junk wanders over. You smell tuna and opportunity.',
    baseCost: 110,
    rate: 1.24,
    unlock: (s) => s.lifetimeCoins >= 90,
    unlockHint: 'Earn 90¢ lifetime',
    section: 'gear',
    next: (lv) => `Luck ${lv + 1}`,
    current: (lv) => `Luck ${lv}`,
  },
];

export const CREW = [
  {
    id: 'intern',
    name: 'Raccoon Intern',
    icon: '🦝',
    desc: 'Scoops while you plot. Paid in pizza crusts and LinkedIn endorsements.',
    baseCost: 150,
    rate: 1.28,
    unlock: (s) => s.lifetimeCoins >= 80,
    unlockHint: 'Earn 80¢ lifetime',
    section: 'crew',
    next: (lv) => `${lv + 1} intern${lv + 1 === 1 ? '' : 's'} on payroll`,
    current: (lv) => (lv ? `${lv} scooping` : 'None yet'),
  },
  {
    id: 'accountant',
    name: 'Uncle Gary Jr.',
    icon: '🎩',
    desc: 'Auto-sells a full bag. Takes 0% and all of the credit.',
    baseCost: 420,
    rate: 1,
    max: 1,
    unlock: (s) => (s.crew.intern || 0) >= 1,
    unlockHint: 'Hire an intern',
    section: 'crew',
    next: (lv) => (lv ? 'Already on payroll' : 'Auto-sell when full'),
    current: (lv) => (lv ? 'Selling' : 'Unemployed'),
  },
  {
    id: 'lookout',
    name: 'Possum Lookout',
    icon: '👀',
    desc: 'Better rares. He is a coward, and that is a skill.',
    baseCost: 380,
    rate: 1.3,
    unlock: (s) => s.locationIndex >= 1,
    unlockHint: 'Reach the grocery',
    section: 'crew',
    next: (lv) => `Rare luck +${(lv + 1) * 8}%`,
    current: (lv) => (lv ? `+${lv * 8}% rares` : 'Asleep'),
  },
  {
    id: 'union',
    name: 'Alley Union',
    icon: '✊',
    desc: 'Global x1.12 multiplier. They demanded a tiny-hat budget.',
    baseCost: 1400,
    rate: 1.42,
    unlock: (s) => s.locationIndex >= 2,
    unlockHint: 'Reach the mall',
    section: 'crew',
    next: (lv) => `Global x${(1.12 ** (lv + 1)).toFixed(2)}`,
    current: (lv) => (lv ? `x${(1.12 ** lv).toFixed(2)}` : 'No contract'),
  },
];

export const BUFFS = {
  frenzy: {
    id: 'frenzy',
    name: 'Dumpster Frenzy',
    icon: '🔥',
    ms: 14000,
    quip: 'Caffeine has entered the raccoon.',
  },
  gold: {
    id: 'gold',
    name: 'Grease Gold Rush',
    icon: '🌟',
    ms: 18000,
    quip: 'Everything is suddenly "artisan."',
  },
  magnet: {
    id: 'magnet',
    name: 'Trash Magnet',
    icon: '🧲',
    ms: 14000,
    quip: 'Junk is sliding toward you like it owes rent.',
  },
  luckstorm: {
    id: 'luckstorm',
    name: 'Lucky Storm',
    icon: '🍀',
    ms: 16000,
    quip: 'The dumpster likes you. Worrying.',
  },
};

export const ACHIEVEMENTS = [
  { id: 'first_scoop', name: 'First Scoop', desc: 'You touched garbage on purpose.', test: (s) => s.stats.scoops >= 1 },
  { id: 'first_sell', name: 'Liquidity Event', desc: 'Sold junk. Became a business.', test: (s) => s.stats.sold >= 1 },
  { id: 'first_buy', name: 'Investor', desc: 'Bought an upgrade with trash money.', test: (s) => Object.entries(s.tree || {}).some(([k, v]) => k !== 'root' && v > 0) || Object.values(s.upgrades || {}).some((v) => v > 0) },
  { id: 'stuffed', name: 'Stuffed', desc: 'Filled the bag like a professional.', test: (s) => s.stats.stuffed >= 1 },
  { id: 'scoops_100', name: 'Wrist Cardio', desc: '100 scoops. The dumpster knows your name.', test: (s) => s.stats.scoops >= 100 },
  { id: 'scoops_1k', name: 'Just Keep Scooping', desc: '1,000 scoops. This is a lifestyle.', test: (s) => s.stats.scoops >= 1000 },
  { id: 'scoops_10k', name: 'Municipal Legend', desc: '10,000 scoops. The mayor has a file.', test: (s) => s.stats.scoops >= 10000 },
  { id: 'rare', name: 'Ooh, Shiny', desc: 'Found something rare in the slime.', test: (s) => s.stats.rares >= 1 },
  { id: 'epic', name: 'Unreasonably Fancy', desc: 'Scooped something epic. It slapped back.', test: (s) => s.stats.epics >= 1 },
  { id: 'legendary', name: 'Absolutely Not Legal', desc: 'A legendary. Hide it from the health inspector.', test: (s) => s.stats.legendaries >= 1 },
  { id: 'mythic', name: 'Cosmic Litter', desc: 'You scooped a myth. The moon noticed.', test: (s) => s.stats.mythics >= 1 },
  { id: 'intern', name: 'Now Hiring', desc: 'An intern scoops for crusts.', test: (s) => (s.crew.intern || 0) >= 1 },
  { id: 'pet', name: 'HR Approved', desc: 'Petted the alley cat. Luck ensued.', test: (s) => s.stats.pets >= 1 },
  { id: 'kick', name: 'Workplace Drama', desc: 'Kicked a possum. He had it coming. Maybe.', test: (s) => s.stats.kicks >= 1 },
  { id: 'combo10', name: 'Hands Blur', desc: 'Hit a 10 scoop combo.', test: (s) => s.stats.maxCombo >= 10 },
  { id: 'combo25', name: 'Raccoon Rain', desc: 'Hit a 25 scoop combo. OSHA left the chat.', test: (s) => s.stats.maxCombo >= 25 },
  { id: 'coins_1k', name: 'Pocket Lint Rich', desc: '1,000¢ lifetime. Tiny tie, big dreams.', test: (s) => s.lifetimeCoins >= 1000 },
  { id: 'coins_1m', name: 'Dumpster Capital', desc: 'A million cents. You are the economy.', test: (s) => s.lifetimeCoins >= 1e6 },
  { id: 'travel', name: 'Bus Person', desc: 'Took the bus to a better dumpster.', test: (s) => s.stats.travels >= 1 },
  { id: 'moon', name: 'No Raccoons in Space', desc: 'Scooped in low orbit anyway.', test: (s) => s.locationIndex >= 8 },
  { id: 'prestige', name: 'Incorporate', desc: 'Reset the empire. Kept the infamy.', test: (s) => s.prestigeCount >= 1 },
  { id: 'codex20', name: 'Connoisseur', desc: 'Discovered 20 kinds of junk.', test: (s) => s.discovered.length >= 20 },
  { id: 'codex40', name: 'Trash Scholar', desc: 'Discovered 40 kinds of junk.', test: (s) => s.discovered.length >= 40 },
  { id: 'schemer', name: 'Schemer', desc: 'Unlocked 8 scheme nodes. The whiteboard is full.', test: (s) => Object.entries(s.tree || {}).filter(([k, v]) => k !== 'root' && v > 0).length >= 8 },
  { id: 'conspiracy', name: 'Conspiracy Board', desc: 'Unlocked 20 scheme nodes. Red string everywhere.', test: (s) => Object.entries(s.tree || {}).filter(([k, v]) => k !== 'root' && v > 0).length >= 20 },
];

export const NEWS = [
  'Mayor: "They have a LinkedIn now."',
  'Local raccoon unionizes dumpster. Tiny hats demanded.',
  'Health inspector found a raccoon. Health inspector joined the raccoon.',
  'Uncle Gary rated "very shady" by Yelp and "very fair" by seagulls.',
  'Study: scooping is cardio if you believe hard enough.',
  'Possum lookout still asleep. Role is "vibes."',
  'Diner neon repaired. It immediately threatened a customer.',
  'You are on the mall Santa list. Twice. Naughty.',
  'NASA denies dumpster on the moon. NASA is lying.',
  'Alley cat accepts pets as tax.',
  'A meatball winked in sector 4. Stay calm.',
  'City council votes to "just keep scooping." Motion passes.',
];

export function trashById(id) {
  return TRASH.find((t) => t.id === id);
}

export function poolFor(locationId, rarity) {
  const local = TRASH.filter((t) => t.rarity === rarity && t.loc === locationId);
  const global = TRASH.filter((t) => t.rarity === rarity && !t.loc);
  return { local, global };
}
